### ISSUE TITLE
Uncaught TYPO3 Exception 1439317802

### ISSUE THREAD

**Issue by r4fx** [fsaris/gravatar#1]
After installing gravatar on TYPO3 7.6 I got an exception
#1439317802: The avatar provider "gravatarProvider" defines an invalid provider. Ensure the class exists and implements the "TYPO3\CMS\Backend\Backend\Avatar\AvatarProviderInterface".

**Comment by fsaris** [comment]
Should be fixed with 0.0.4 what version did you use?

**Comment by r4fx** [comment]
I use latest version 0.0.5

**Comment by fsaris** [comment]
You installed it from TER? Just downloaded is in the extension manager and did a install?

**Comment by fsaris** [comment]
Ok, just tested install from TER and seems that all classes are missing. Will upload a new version

**Comment by fsaris** [comment]
New version is uploaded to TER. 0.0.6 and should fix the issue. 

Tnx for you report.
My apologies for the inconvenience

gr. Frans
