### ISSUE TITLE
Feature: Use uploaded image even if mail is set

### ISSUE THREAD

**Issue by mhirdes** [fsaris/gravatar#6]
Hey,

thanks for your extension. It works very well.

Our costumers don't want to create a gravatar profile but we have to add their mail adress in the backend, too. It would be a nice option, that even if a mail address is set, also the uploaded image could be used, if no gravatar profile was found.

Kind regards,
Marc

**Comment by frans-beech-it** [comment]
That is possible. The uploaded images wins from the gravatar

**Comment by fsaris** [comment]
was fixed with https://github.com/fsaris/gravatar/pull/3
